# Generated by Django 3.2 on 2021-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
