# Generated by Django 3.2 on 2021-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=300)),
                ('seller', models.ManyToManyField(related_name='sellers', to='seller.Seller')),
            ],
        ),
    ]
