# Generated by Django 3.2 on 2021-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=50)),
                ('skillPrice', models.CharField(max_length=50)),
                ('skillImage', models.CharField(max_length=300)),
            ],
        ),
    ]
