# Generated by Django 3.2 on 2021-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20210415_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_price',
        ),
        migrations.AddField(
            model_name='skill',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
