# Generated by Django 3.2 on 2021-04-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='seller',
        ),
    ]
