# Generated by Django 3.2 on 2021-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('skills', '0004_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='seller',
            field=models.ManyToManyField(related_name='sellers', to='seller.Seller'),
        ),
    ]
